version: '2'

services:
    postgresql:
        restart: always
        image: sameersbn/postgresql:9.5-1
        volumes:
            - /srv/docker/tendenci/postgresql:/var/lib/postgresql:Z
        environment:
            - DB_USER=tendenci
            - DB_NAME=tendenci
            - DB_PASS=password
            - DB_EXTENSION=postgis,postgis_topology,fuzzystrmatch,postgis_tiger_geocoder
        networks:
            - backend

    tendenci:
        restart: always
        image: frenchbeard/tendenci:0.1.0
        volumes:
            - /srv/docker/tendenci/app/logs:/var/log/tendenci:Z
            - /srv/docker/tendenci/app/data:/home/tendenci/data:Z
        depends_on:
            - postgresql
        expose:
            - 8000
        networks:
            - backend
        environment:
            # Postgresql setup
            - DB_USER=tendenci
            - DB_NAME=tendenci
            - DB_PASS=password
            - DB_HOST=postgresql
            - DB_PORT=5432

            # Superuser setup
            - ADMIN_USER=admin
            - ADMIN_MAIL=admin@example.com
            - ADMIN_PASS=password

networks:
    backend:
        driver: bridge
